//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMech.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePrisut
    {
        public int IdPrisut { get; set; }
        public int IdStudent { get; set; }
        public int IdGroup { get; set; }
        public string FIO { get; set; }
        public string GroupName { get; set; }
        public System.DateTime Date { get; set; }
        public string Prisut { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Student Student { get; set; }
    }
}
