//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMech.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePay
    {
        public int IdPay { get; set; }
        public string FIO { get; set; }
        public System.DateTime DatePay { get; set; }
        public System.DateTime DateStart { get; set; }
        public int IdStudent { get; set; }
        public string CountPay { get; set; }
        public string TypePay { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
